(() => {
  const baseData = window.PORTFOLIO_DATA;
  let data = baseData;
  try { const override = localStorage.getItem('portfolioOverride'); if (override) data = JSON.parse(override); } catch (e) { console.warn('Portfolio override ignored:', e); }
  let lang = localStorage.getItem('portfolioLanguage') || data.meta.defaultLanguage || 'en';
  let activeFilter = 'all';
  const labels = {
    en:{nav:[['home','Home'],['about','Expertise'],['projects','Projects'],['experience','Experience'],['leadership','Leadership'],['achievements','Achievements'],['contact','Contact']],viewProjects:'View selected projects',downloadCV:'Download CV',whatIDo:'What I do',capabilitiesTitle:'Geospatial expertise from field to digital product.',capabilitiesIntro:'A practical combination of field surveying, spatial analysis, remote sensing, and product development.',selectedWork:'Selected work',projectsTitle:'Projects built to be useful, accurate, and accessible.',projectsIntro:'A selection of live products, WebGIS applications, mapping work, environmental analysis, and GeoAI experimentation.',careerPath:'Career path',experienceTitle:'Hands-on experience across survey, government, and community projects.',experienceIntro:'Field execution, stakeholder coordination, spatial data production, and technical quality control.',beyondTechnical:'Beyond technical work',leadershipTitle:'Leadership that turns plans into delivery.',leadershipIntro:'Experience coordinating teams, budgets, technical training, partnerships, and nationwide organizational collaboration.',recognition:'Recognition',achievementsTitle:'Achievements & selected recognition.',achievementsIntro:'Academic, technical, scholarship, and competition milestones that reflect consistent learning and contribution.',toolkit:'Toolkit',skillsTitle:'Tools, methods, and working strengths.',skillsIntro:'A broad technical foundation supported by communication, leadership, and stakeholder coordination.',academic:'Academic foundation',educationTitle:'Education',letsConnect:'Let’s connect',contactTitle:'Need a GIS, surveying, drone, or WebGIS collaborator?',contactIntro:'I am open to professional opportunities, project collaboration, technical discussions, and geospatial problem-solving.',footerTagline:'GIS, surveying, drone mapping, remote sensing, and digital geospatial products.',contentEditor:'Open content editor',all:'All',webgis:'Web / WebGIS',remote:'Remote Sensing / GeoAI',mapping:'Mapping',survey:'Survey',details:'Project details',live:'Open live project',source:'View source',technical:'Technical skills',soft:'Working strengths',languages:'Languages',email:'Email me',whatsapp:'WhatsApp',linkedin:'LinkedIn',github:'GitHub',oldPortfolio:'Portfolio archive'},
    id:{nav:[['home','Beranda'],['about','Keahlian'],['projects','Project'],['experience','Pengalaman'],['leadership','Kepemimpinan'],['achievements','Prestasi'],['contact','Kontak']],viewProjects:'Lihat project pilihan',downloadCV:'Unduh CV',whatIDo:'Keahlian saya',capabilitiesTitle:'Keahlian geospasial dari lapangan hingga produk digital.',capabilitiesIntro:'Kombinasi praktis survei lapangan, analisis spasial, penginderaan jauh, dan pengembangan produk.',selectedWork:'Karya pilihan',projectsTitle:'Project yang dirancang agar berguna, akurat, dan mudah diakses.',projectsIntro:'Pilihan produk live, aplikasi WebGIS, karya pemetaan, analisis lingkungan, dan eksperimen GeoAI.',careerPath:'Perjalanan karier',experienceTitle:'Pengalaman langsung dalam survei, pemerintahan, dan project masyarakat.',experienceIntro:'Eksekusi lapangan, koordinasi pemangku kepentingan, produksi data spasial, dan kendali mutu teknis.',beyondTechnical:'Di luar kemampuan teknis',leadershipTitle:'Kepemimpinan yang mengubah rencana menjadi hasil.',leadershipIntro:'Pengalaman mengoordinasikan tim, anggaran, pelatihan teknis, kemitraan, dan kolaborasi organisasi tingkat nasional.',recognition:'Pengakuan',achievementsTitle:'Prestasi & pengakuan terpilih.',achievementsIntro:'Tonggak akademik, teknis, beasiswa, dan kompetisi yang mencerminkan konsistensi belajar dan berkontribusi.',toolkit:'Perangkat kerja',skillsTitle:'Alat, metode, dan kekuatan kerja.',skillsIntro:'Fondasi teknis yang luas didukung komunikasi, kepemimpinan, dan koordinasi pemangku kepentingan.',academic:'Fondasi akademik',educationTitle:'Pendidikan',letsConnect:'Mari terhubung',contactTitle:'Membutuhkan kolaborator GIS, survei, drone, atau WebGIS?',contactIntro:'Saya terbuka untuk peluang profesional, kolaborasi project, diskusi teknis, dan pemecahan masalah geospasial.',footerTagline:'GIS, survei, pemetaan drone, penginderaan jauh, dan produk digital geospasial.',contentEditor:'Buka editor konten',all:'Semua',webgis:'Web / WebGIS',remote:'Penginderaan Jauh / GeoAI',mapping:'Pemetaan',survey:'Survei',details:'Detail project',live:'Buka project live',source:'Lihat source',technical:'Keahlian teknis',soft:'Kekuatan kerja',languages:'Bahasa',email:'Kirim email',whatsapp:'WhatsApp',linkedin:'LinkedIn',github:'GitHub',oldPortfolio:'Arsip portofolio'}
  };
  const $ = (s,root=document)=>root.querySelector(s); const $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const tr = v => (v && typeof v === 'object' && !Array.isArray(v)) ? (v[lang] ?? v.en ?? Object.values(v)[0]) : v;
  const iconSvg = name => ({
    map:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m3 6 5-3 8 3 5-3v15l-5 3-8-3-5 3V6Z"/><path d="M8 3v15M16 6v15"/></svg>',
    survey:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v4M6 21l6-14 6 14M8 16h8M4 21h16"/><circle cx="12" cy="6" r="2"/></svg>',
    drone:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M8 12h8M10 9h4l2 6H8l2-6Z"/><path d="M5 8 3 6M19 8l2-2M5 16l-2 2M19 16l2 2"/><circle cx="4" cy="7" r="2"/><circle cx="20" cy="7" r="2"/><circle cx="4" cy="17" r="2"/><circle cx="20" cy="17" r="2"/></svg>',
    code:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m8 9-4 3 4 3M16 9l4 3-4 3M14 5l-4 14"/></svg>',
    satellite:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m13 7 4-4 4 4-4 4-4-4Z"/><path d="m3 17 4-4 4 4-4 4-4-4ZM9 15l6-6M5 9a10 10 0 0 1 10 10M5 5a14 14 0 0 1 14 14"/></svg>',
    database:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg>',
    sun:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
    moon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 15.4A9 9 0 1 1 8.6 4 7 7 0 0 0 20 15.4Z"/></svg>'
  }[name]||'');
  function setText(){ document.documentElement.lang=lang; $$('[data-label]').forEach(el=>{const k=el.dataset.label;if(labels[lang][k])el.textContent=labels[lang][k]}); $('#langToggle').innerHTML=`<span class="${lang==='en'?'active':''}">EN</span><span class="${lang==='id'?'active':''}">ID</span>`; }
  function renderNav(){ $('#siteNav').innerHTML=labels[lang].nav.map(([id,label])=>`<a href="#${id}">${label}</a>`).join(''); }
  function renderHero(){ const p=data.profile; $('#availability').textContent=tr(p.availability); $('#heroName').textContent=p.name; $('#heroRole').textContent=tr(p.role); $('#heroHeadline').textContent=tr(p.headline); $('#heroSummary').textContent=tr(p.summary); $('#profilePhoto').src=p.photo; $('#resumeLink').href=p.resume; $('#heroContacts').innerHTML=`<a class="contact-chip" href="mailto:${p.email}">✉ ${p.email}</a><a class="contact-chip" href="https://wa.me/${p.phone}" target="_blank" rel="noopener">◉ ${p.phoneDisplay}</a><span class="contact-chip">⌖ ${p.location}</span>`; $('#statsGrid').innerHTML=data.stats.map(s=>`<div class="stat"><strong>${s.value}</strong><span>${tr(s.label)}</span></div>`).join(''); }
  function renderCapabilities(){ $('#capabilityGrid').innerHTML=data.capabilities.map((c,i)=>`<article class="capability-card reveal" style="transition-delay:${i*.05}s"><div class="icon-box">${iconSvg(c.icon)}</div><h3>${tr(c.title)}</h3><p>${tr(c.description)}</p></article>`).join(''); }
  function renderProjects(){ const filters=['all','webgis','remote','mapping','survey']; $('#projectFilters').innerHTML=filters.map(f=>`<button class="filter-button ${activeFilter===f?'active':''}" data-filter="${f}">${labels[lang][f]}</button>`).join(''); const visible=data.projects.filter(p=>activeFilter==='all'||p.category===activeFilter); $('#projectsGrid').innerHTML=visible.map((p,i)=>`<article class="project-card ${p.featured?'featured':''} reveal" data-project="${p.id}"><div class="project-image"><img src="${p.image}" alt="${tr(p.title)} preview" loading="lazy"><span class="project-badge">${p.year}${p.id==='jagasleman'?' • NEW':''}</span></div><div class="project-body"><div class="project-kicker">${tr(p.kicker)}</div><h3>${tr(p.title)}</h3><p>${tr(p.description)}</p><div class="tag-row">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="project-links">${p.live?`<a class="text-link" href="${p.live}" target="_blank" rel="noopener">${labels[lang].live} ↗</a>`:''}${p.source?`<a class="text-link" href="${p.source}" target="_blank" rel="noopener">${labels[lang].source} ↗</a>`:''}<button class="text-link details-button" data-id="${p.id}">${labels[lang].details} +</button></div></div></article>`).join(''); $$('.filter-button').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;renderProjects();initReveal();}); $$('.details-button').forEach(b=>b.onclick=e=>{e.preventDefault();openProject(b.dataset.id)}); initReveal(); }
  function renderExperience(){ $('#experienceTimeline').innerHTML=data.experience.map((e,i)=>`<article class="timeline-item reveal"><div class="timeline-meta"><span>${e.location}</span><span>${e.period}</span></div><h3>${e.organization}</h3><div class="timeline-role">${e.role}</div><ul>${tr(e.highlights).map(h=>`<li>${h}</li>`).join('')}</ul></article>`).join(''); }
  function renderLeadership(){ $('#leadershipGrid').innerHTML=data.organizations.map((o,i)=>`<article class="leadership-card reveal"><div class="number-box">0${i+1}</div><div><h3>${o.name}</h3><div class="leadership-role">${tr(o.role)} • ${o.period}</div><p>${tr(o.detail)}</p></div></article>`).join(''); }
  function renderAchievements(){ $('#achievementList').innerHTML=data.achievements.map(a=>`<article class="achievement-item reveal"><div class="achievement-year">${a.year}</div><h3>${tr(a.title)}</h3><p>${tr(a.description)}</p><div class="achievement-arrow">↗</div></article>`).join(''); }
  function renderSkills(){ const groups=[[labels[lang].technical,data.skills.technical],[labels[lang].soft,data.skills.soft],[labels[lang].languages,data.skills.languages]]; $('#skillsPanels').innerHTML=groups.map(g=>`<section class="skill-panel reveal"><h3>${g[0]}</h3><div class="chip-cloud">${g[1].map(s=>`<span class="skill-chip">${s}</span>`).join('')}</div></section>`).join(''); }
  function renderEducation(){ $('#educationGrid').innerHTML=data.education.map(e=>`<article class="education-card reveal"><h3>${e.school}</h3><div class="program">${tr(e.program)}</div><div class="period">${e.period}</div><div class="note">${tr(e.note)}</div></article>`).join(''); }
  function renderContact(){ const p=data.profile; $('#contactActions').innerHTML=`<a class="button" href="mailto:${p.email}"><span>${labels[lang].email}</span><span>↗</span></a><a class="button" href="https://wa.me/${p.phone}" target="_blank" rel="noopener"><span>${labels[lang].whatsapp}</span><span>↗</span></a><a class="button" href="${p.linkedin}" target="_blank" rel="noopener"><span>${labels[lang].linkedin}</span><span>↗</span></a><a class="button" href="${p.github}" target="_blank" rel="noopener"><span>${labels[lang].github}</span><span>↗</span></a>`; $('#footerLinks').innerHTML=`<a href="${p.linkedin}" target="_blank" rel="noopener">LinkedIn</a><a href="${p.github}" target="_blank" rel="noopener">GitHub</a><a href="${p.oldPortfolio}" target="_blank" rel="noopener">${labels[lang].oldPortfolio}</a><a href="${p.resume}" download>CV</a>`; }
  function openProject(id){ const p=data.projects.find(x=>x.id===id); if(!p)return; $('#modalContent').innerHTML=`<img class="modal-image" src="${p.image}" alt="${tr(p.title)}"><div class="modal-body"><div class="project-kicker">${tr(p.kicker)} • ${p.year}</div><h2>${tr(p.title)}</h2><p>${tr(p.description)}</p><div class="tag-row">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="project-links">${p.live?`<a class="button primary" href="${p.live}" target="_blank" rel="noopener">${labels[lang].live} ↗</a>`:''}${p.source?`<a class="button secondary" href="${p.source}" target="_blank" rel="noopener">${labels[lang].source} ↗</a>`:''}</div></div>`; $('#projectModal').showModal(); }
  let observer; function initReveal(){ if(observer)observer.disconnect(); observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1}); $$('.reveal').forEach(el=>observer.observe(el)); }
  function setupTheme(){ const saved=localStorage.getItem('portfolioTheme'); const current=saved||'dark'; document.documentElement.dataset.theme=current; $('#themeToggle').innerHTML=iconSvg(current==='dark'?'sun':'moon'); $('#themeToggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('portfolioTheme',next);$('#themeToggle').innerHTML=iconSvg(next==='dark'?'sun':'moon')}; }
  function setupInteractions(){ $('#langToggle').onclick=()=>{lang=lang==='en'?'id':'en';localStorage.setItem('portfolioLanguage',lang);renderAll()}; $('#menuToggle').onclick=()=>{const n=$('#siteNav');n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',n.classList.contains('open'))}; $$('#siteNav a').forEach(a=>a.onclick=()=>$('#siteNav').classList.remove('open')); $('#modalClose').onclick=()=>$('#projectModal').close(); $('#projectModal').onclick=e=>{if(e.target===$('#projectModal'))$('#projectModal').close()}; $('#backToTop').onclick=()=>scrollTo({top:0,behavior:'smooth'}); addEventListener('scroll',()=>{$('.site-header').classList.toggle('scrolled',scrollY>20);$('#backToTop').classList.toggle('visible',scrollY>650)}); const sections=$$('main section[id]'); const navObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){$$('#siteNav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-45% 0px -50%'});sections.forEach(s=>navObs.observe(s)); }
  function renderAll(){setText();renderNav();renderHero();renderCapabilities();renderProjects();renderExperience();renderLeadership();renderAchievements();renderSkills();renderEducation();renderContact();$('#year').textContent=new Date().getFullYear();setupInteractions();initReveal();}
  setupTheme(); renderAll();
})();
